accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("", views.index, name="index"),
    path('<int:pk>/', views.detail, name='detail'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/update/', views.update, name='update'),  
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:_id>/', views.detail, name='detail'),
    path('<int:_id>/update/', views.update, name='update'),
    path('<int:_id>/delete/', views.delete, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

reviews/models.py
from django.db import models

# Create your models here.
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    grade = models.FloatField(validators=[MinValueValidator(0.0),MaxValueValidator(5.0)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# from .models import User
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )
class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'email'
            )

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):

    class Meta():
        model = Review
        fields = ['title', 'content', 'movie_name', 'grade']

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required


def signup(request):
 def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() # ModelForm의 save 메서드의 리턴값은 해당 모델의 인스턴스다!
            auth_login(request, user) # 로그인
            return redirect('accounts:index')
    else:   
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def index(request):
    users = User.objects.all()
    # Template에 전달한다.
    context = {"users": users}
    return render(request, "accounts/index.html", context)

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

def update(request,pk):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail',request.user.pk)
    else:
        user = get_user_model().objects.get(pk=pk)
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
        'user': user
    }
    return render(request, 'accounts/update.html',context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

reviews/views.py
from django.shortcuts import redirect, render
from .models import Review
from .forms import ReviewForm
from django.core.paginator import Paginator


def create(req):
    if req.method == 'POST':
        data = ReviewForm(req.POST)

        if data.is_valid():
            # form 으로 부터 받은 데이터를 가져오기
            db_data = data.save(commit=False)
            db_data.save()

            return redirect('reviews:index')

    else:
        data = ReviewForm()

    return render(req, 'reviews/create.html', {'data': data})


# ref(pagination) : https://velog.io/@jewon119/Django-%EA%B8%B0%EC%B4%88-ListView
def index(req):
    data = Review.objects.all().order_by('-id')

    # review_list 페이징 처리
    page = req.GET.get('page') #GET 방식으로 정보를 받아오는 데이터
    paginator = Paginator(data, '10') #Paginator(분할될 객체, 페이지 당 담길 객체수)
    page_obj = paginator.get_page(page) #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장

    return render(req, 'reviews/index.html', {'data': data, 'page': page_obj})


def detail(req, _id):
    db_data = Review.objects.get(id=_id)

    return render(req, 'reviews/detail.html', {'data': db_data})


def update(req, _id):
    db_data = Review.objects.get(id=_id)

    if req.method == 'POST':
        data = ReviewForm(req.POST, instance=db_data)

        if data.is_valid():
            data.save()

            return redirect('reviews:index')

    else:
        data = ReviewForm(instance=db_data)

    return render(req, 'reviews/create.html', {'data': data})


def delete(req, _id):
    Review.objects.get(id=_id).delete()

    return redirect('reviews:index')

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ user.username }}님의 프로필</h1>
<p>{{ user.last_name }} {{ user.first_name }} | {{ user.email }}</p>

{% endblock body %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}
<h1>회원정보</h1>
<td><a href="{% url 'accounts:signup'  %}">회원가입</a></td>
<table class="table text-center align-middle">
    <thead>
        <th>ID</th>
        <th>username</th>
        <th>e-mail</th>
        <th>생성 날짜</th>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{user.id}}</td>
            <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
            <td>{{user.email}}</td>
            <td>{{user.date_joined}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<hr>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>회원가입</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>

{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>프로필 업데이트</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock body %}

pjt/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% bootstrap_css %}
  {% block css %}{% endblock css %}
</head>
<body>

  {% if request.user.is_authenticated %}
    <span> <a href="{% url 'accounts:detail' user.pk  %}">{{ request.user }}</a> </span>
    <a href="{% url 'reviews:create' %}">리뷰 작성</a>
    <a href="{% url 'reviews:index' %}">리뷰 목록</a>
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    <a href="{% url 'accounts:update' user.pk  %}">정보수정</a>
  {% else %}
    <a href="{% url 'reviews:index' %}">리뷰 목록</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    <a href="{% url 'accounts:login' %}">로그인</a>  
  {% endif %}

  <div class="container my-5">
    {% block body %}{% endblock body %}
  </div>
  {% bootstrap_javascript %}
</body>

</html>

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
    <h1>생성</h1>
{% else %}c
    <h1>수정</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form data %}

    {% bootstrap_button button_type="submit" content="OK" %}
</form>

{% endblock body %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
<h1>수정</h1>
<h3>영화 : {{ data.movie_name }}</h3>
<p>평점 : {{ data.grade }}</p>
<p>내용 : {{ data.content }}</p>
<p>{{ data.created_at }} | <span>{{ data.updated_at }}</span></p>

 
<div class="buttons d-flex">
  <a class="me-3" href="{% url 'reviews:update' data.id %}">{% bootstrap_button button_class="btn btn-outline-success" content="수정" %}</a>
  <div>
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
      삭제
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Warning</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Do you really want to delete it?
          </div>
          <div class="modal-footer">
            <a href="{% url 'reviews:delete' data.id %}">
              <button type="button" class="btn btn-primary">Yes</button>
            </a>  
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load static %}



{% block body %}
<h1>Movies</h1>
<table class="table align-middle">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">Movie Name</th>
      <th scope="col">Grade</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <!-- 넘겨받은 페이지 객체만큼 반복한다. -->
    {% for i in page %}
    <tr>
      <td class="fw-bold"><a href="{% url 'reviews:detail' i.id %}">{{ i.title }}</a></td>
      <td>{{ i.content }}</td>
      <td>{{ i.movie_name }}</td>
      <td>{{ i.grade }}</td>
      <td>{{ i.created_at }}</td>
      <td>{{ i.updated_at }}</td>
    </tr>
    {% endfor %} 
  </tbody>
</table>
<div class="d-flex justify-content-end">
  <a href="{% url 'reviews:create' %}">
    <button type="button" class="btn btn-primary mb-3">New Movie</button>
  </a>
</div>

<!-- ref(Disabled and active states) : https://getbootstrap.com/docs/5.2/components/pagination/ -->
<!-- 페이징처리 시작 -->
<nav aria-label="pagination" class="d-flex justify-content-center">
  <ul class="pagination">
    <!-- previous -->
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Previous</a>
    </li>
    {% endif %}

    <!-- pages -->
    <!-- page.paginator.page_range : [1, ..., max] -->
    {% for i in page.paginator.page_range %}
      {% if i == page.number %}
      <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ i }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    
    <!-- next -->
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
<!-- 페이징처리 끝 -->



{% endblock body %}